// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SGMA.Infrastructure.Data;

#nullable disable

namespace SGMA.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20261009183333_CreaCatalogos")]
    partial class CreaCatalogos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SGMA.Domain.Entities.EstadoActivo", b =>
                {
                    b.Property<int>("IdEstadoActivo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEstadoActivo"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("IdEstadoActivo")
                        .HasName("PK_EstadoActivo");

                    b.HasIndex(new[] { "Nombre" }, "UQ_EstadoActivo_Nombre")
                        .IsUnique();

                    b.ToTable("EstadoActivo");

                    b.HasData(
                        new
                        {
                            IdEstadoActivo = 1,
                            Nombre = "Operativo"
                        },
                        new
                        {
                            IdEstadoActivo = 2,
                            Nombre = "En Mantenimiento"
                        },
                        new
                        {
                            IdEstadoActivo = 3,
                            Nombre = "Fuera de Servicio"
                        },
                        new
                        {
                            IdEstadoActivo = 4,
                            Nombre = "Dado de Baja"
                        });
                });

            modelBuilder.Entity("SGMA.Domain.Entities.EstadoOrden", b =>
                {
                    b.Property<int>("IdEstadoOrden")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEstadoOrden"));

                    b.Property<bool>("EsFinal")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("IdEstadoOrden")
                        .HasName("PK_EstadoOrden");

                    b.HasIndex(new[] { "Nombre" }, "UQ_EstadoOrden_Nombre")
                        .IsUnique();

                    b.ToTable("EstadoOrden");

                    b.HasData(
                        new
                        {
                            IdEstadoOrden = 1,
                            EsFinal = false,
                            Nombre = "Solicitada"
                        },
                        new
                        {
                            IdEstadoOrden = 2,
                            EsFinal = false,
                            Nombre = "Diagnosticada"
                        },
                        new
                        {
                            IdEstadoOrden = 3,
                            EsFinal = false,
                            Nombre = "Aprobada"
                        },
                        new
                        {
                            IdEstadoOrden = 4,
                            EsFinal = true,
                            Nombre = "Rechazada"
                        },
                        new
                        {
                            IdEstadoOrden = 5,
                            EsFinal = false,
                            Nombre = "En Ejecución"
                        },
                        new
                        {
                            IdEstadoOrden = 6,
                            EsFinal = false,
                            Nombre = "En Espera de Repuesto"
                        },
                        new
                        {
                            IdEstadoOrden = 7,
                            EsFinal = true,
                            Nombre = "Completada"
                        },
                        new
                        {
                            IdEstadoOrden = 8,
                            EsFinal = true,
                            Nombre = "Cancelada"
                        });
                });

            modelBuilder.Entity("SGMA.Domain.Entities.NaturalezaMantenimiento", b =>
                {
                    b.Property<int>("IdNaturaleza")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdNaturaleza"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("IdNaturaleza")
                        .HasName("PK_NaturalezaMantenimiento");

                    b.HasIndex(new[] { "Nombre" }, "UQ_NaturalezaMantenimiento_Nombre")
                        .IsUnique();

                    b.ToTable("NaturalezaMantenimiento");

                    b.HasData(
                        new
                        {
                            IdNaturaleza = 1,
                            Nombre = "Preventivo"
                        },
                        new
                        {
                            IdNaturaleza = 2,
                            Nombre = "Correctivo"
                        },
                        new
                        {
                            IdNaturaleza = 3,
                            Nombre = "Emergencia"
                        });
                });

            modelBuilder.Entity("SGMA.Domain.Entities.NivelCertificacion", b =>
                {
                    b.Property<int>("IdNivelCertificacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdNivelCertificacion"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("IdNivelCertificacion")
                        .HasName("PK_NivelCertificacion");

                    b.HasIndex(new[] { "Nombre" }, "UQ_NivelCertificacion_Nombre")
                        .IsUnique();

                    b.ToTable("NivelCertificacion");

                    b.HasData(
                        new
                        {
                            IdNivelCertificacion = 1,
                            Nombre = "Básico"
                        },
                        new
                        {
                            IdNivelCertificacion = 2,
                            Nombre = "Intermedio"
                        },
                        new
                        {
                            IdNivelCertificacion = 3,
                            Nombre = "Avanzado"
                        },
                        new
                        {
                            IdNivelCertificacion = 4,
                            Nombre = "Experto"
                        });
                });

            modelBuilder.Entity("SGMA.Domain.Entities.Prioridad", b =>
                {
                    b.Property<int>("IdPrioridad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPrioridad"));

                    b.Property<short>("Nivel")
                        .HasColumnType("smallint");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("IdPrioridad")
                        .HasName("PK_Prioridad");

                    b.HasIndex(new[] { "Nombre" }, "UQ_Prioridad_Nombre")
                        .IsUnique();

                    b.ToTable("Prioridad");

                    b.HasData(
                        new
                        {
                            IdPrioridad = 1,
                            Nivel = (short)1,
                            Nombre = "Baja"
                        },
                        new
                        {
                            IdPrioridad = 2,
                            Nivel = (short)2,
                            Nombre = "Media"
                        },
                        new
                        {
                            IdPrioridad = 3,
                            Nivel = (short)3,
                            Nombre = "Alta"
                        },
                        new
                        {
                            IdPrioridad = 4,
                            Nivel = (short)4,
                            Nombre = "Crítica"
                        });
                });

            modelBuilder.Entity("SGMA.Domain.Entities.Rol", b =>
                {
                    b.Property<int>("IdRol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRol"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("IdRol")
                        .HasName("PK_Rol");

                    b.HasIndex(new[] { "Nombre" }, "UQ_Rol_Nombre")
                        .IsUnique();

                    b.ToTable("Rol");

                    b.HasData(
                        new
                        {
                            IdRol = 1,
                            Nombre = "Administrador"
                        },
                        new
                        {
                            IdRol = 2,
                            Nombre = "Coordinador/Técnico"
                        },
                        new
                        {
                            IdRol = 3,
                            Nombre = "Solicitante/Consulta"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
